project:
  type: website
  output-dir: docs

website:
  title: "My Analytical Story"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022
format:
  html:
   css: styles.css



